apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: full-stack-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: full-stack-app
spec:
  selector:
    matchLabels:
      pod: mongo-pod
  template:
    metadata:
      labels:
        app: full-stack-app
        pod: mongo-pod
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data
              subPath: db
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: dbpass
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: full-stack-app
spec:
  ports:
   - port: 27017
  selector:
   pod: mongo-pod
